version: 2

references:
  workspace: &workspace
      ~/workspace

  #android configuration
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m

  #gcloud config
  gcloud_config: &gcloud_config
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
      TERM: dumb

  # Google Services

  export_gservices_key: &export_gservices_key
    run:
      name: Export Google Services key environment variable
      command: echo 'export GOOGLE_SERVICES_KEY="$GOOGLE_SERVICES_KEY"' >> $BASH_ENV
  decode_gservices_key: &decode_gservices_key
    run:
      name: Decode Google Services key
      command: echo $GOOGLE_SERVICES_KEY | base64 -di > mobile/google-services.json

  # Google Cloud Service

  export_gcloud_key: &export_gcloud_key
    run:
      name: Export Google Cloud Service key environment variable
      command: echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
  decode_gcloud_key: &decode_gcloud_key
    run:
      name: Decode Google Cloud credentials
      command: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/client-secret.json

  default_steps: &default_steps
    - restore_gradle_cache: &restore_gradle_cache
        restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run: &download_dependencies
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_gradle_cache: &save_gradle_cache
        save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  persist_lib_artifacts: &persist_lib_artifacts
      persist_to_workspace:
          root: *workspace
          paths:
            - testlibrary/build/libs
            - testlibrary/build/zips
  attach_lib_artifacts: &attach_lib_artifacts
      attach_workspace:
          at: *workspace
  persist_instrumentation_test: &persist_instrumentation_test
      persist_to_workspace:
          root: *workspace
          paths:
            - app/build/outputs/apk
  attach_instrumentation_test: &attach_instrumentation_test
      attach_workspace:
          at: *workspace

jobs:
  build_and_unit_test:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - run:
          name: Run Unit Tests
          command: ./gradlew lint test
      - run:
          name: Generate Android Instrumentation Test
          command: ./gradlew assembleDebug assembleAndroidTest
      - run:
          name: Generate Library
          command: ./gradlew jarrelease
      - run:
          name: Generate Zip
          command: ./gradlew ziprelease
      - *persist_lib_artifacts
      - *persist_instrumentation_test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          name: Store App Test Result
          path: app/build/test-results
      - store_test_results:
          name: Store Lib Test Result
          path: testlibrary/build/test-results
  instrumentation_test:
    <<: *gcloud_config
    steps:
      - *attach_instrumentation_test
      - *export_gcloud_key
      - *decode_gcloud_key
  deploy:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *attach_lib_artifacts
      - store_artifacts:
          path: testlibrary/build/zips
          destination: zips

workflows:
  version: 2
  build_unit_instrumentation_test_deploy:
    jobs:
      - build_and_unit_test
      - instrumentation_test:
          requires:
            - build_and_unit_test
      - deploy:
          requires:
            - instrumentation_test