version: 2

references:
  #android configuration
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
  default_steps: &default_steps
    - restore_gradle_cache: &restore_gradle_cache
        restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run: &download_dependencies
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_gradle_cache: &save_gradle_cache
        save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  workspace: &workspace
      ~/workspace
  persist_lib_artifacts: &persist_lib_artifacts
      persist_to_workspace:
          root: *workspace
          paths:
            - testlibrary/build/libs
            - testlibrary/build/zips
  attach_lib_artifacts: &attach_lib_artifacts
      attach_workspace:
          at: *workspace

jobs:
  build_and_unit_test:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - run:
          name: Run Unit Tests
          command: ./gradlew lint test
      - run:
          name: Release App
          command: ./gradlew assembleRelease
      - run:
          name: Generate Library
          command: ./gradlew jarrelease
      - run:
          name: Generate Zip
          command: ./gradlew ziprelease
      - *persist_lib_artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          name: Store App Test Result
          path: app/build/test-results
      - store_test_results:
          name: Store Lib Test Result
          path: testlibrary/build/test-results
  deploy:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *attach_lib_artifacts
      - store_artifacts:
          path: testlibrary/build/zips
          destination: zips

workflows:
  version: 2
  build_and_unit_deploy:
    jobs:
      - build_and_unit_test
      - deploy:
          requires:
            - build_and_unit_test