version: 2

references:
  android_config: &android_config
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
  default_steps: &default_steps
    - checkout
    - restore_gradle_cache: &restore_gradle_cache
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run: &download_dependencies
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_gradle_cache: &save_gradle_cache
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - checkout
#      - *restore_cache
#      - *download_dependencies
#      - *save_chave
      - run:
          name: Run Unit Tests
          command: ./gradlew lint test
      - run:
          name: Release App
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          name: Store App Test Result
          path: app/build/test-results
      - store_test_results:
          name: Store Lib Test Result
          path: testlibrary/build/test-results
  deploy:
    <<: *android_config
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Generate Library JAr and Zip
          command: ./gradlew jarrelease ziprelease
      - store_artifacts:
          path: testlibrary/build/zips
          destination: zips

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build